---
- name: restart nova-api
  sudo: yes
  service: name=openstack-nova-api state=restarted

- name: restart nova-compute
  sudo: yes
  service: name=openstack-nova-compute state=restarted

- name: restart glance-api
  sudo: yes
  service: name=openstack-glance-api state=restarted

- name: restart glance-registry
  sudo: yes
  service: name=openstack-glance-registry state=restarted

- name: restart cinder-api
  sudo: yes
  service: name=openstack-cinder-api state=restarted

- name: restart neutron-api
  sudo: yes
  service: name=neutron-server state=restarted

- name: restart httpd
  sudo: yes
  service: name=httpd state=restarted

- name: restart sssd
  service: name=sssd state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted
