---

- name: install freeipa packages
  tags:
    - ipaserver
  yum: name={{ item }} state=present
  with_items:
    - bind-dyndb-ldap
    - firewalld
    - freeipa-server
    - bind-pkcs11
    - bind-pkcs11-utils
  when: ansible_distribution == 'Fedora'


- name: ipa packages
  tags:
    - ipaserver
  yum: name={{ item }} state=present
  with_items:
    - bind-dyndb-ldap
    - firewalld
    - ipa-server
    - bind-pkcs11
    - bind-pkcs11-utils
    - ipa-server-dns
  when: ansible_distribution == "RedHat"  or ansible_distribution == 'CentOS'

- name: install ipa
  tags:
    - ipaserver
  command: >
    ipa-server-install -U
    --realm {{ ipa_realm }}
    --domain {{ ipa_realm | lower }}
    --ds-password {{ ipa_dm_password }}
    --admin-password {{ ipa_admin_password }}
    --setup-dns
    --ip-address {{ ansible_default_ipv4.address }}
    --forwarder {{ ipa_dns_forwarder }}
  args:
    creates: /etc/ipa/ca.crt

- name: install ipa kra
  tags:
    - ipaserver
  command: >
    ipa-kra-install -U
    -p {{ ipa_dm_password }}
  args:
    creates: /etc/httpd/alias/kra-agent.pem
  when: ansible_distribution == "RedHat"

- name: enable firewalld
  tags:
    - ipaserver
  service: enabled=yes
	   state=started
	   name=firewalld

- name: Open Firewall for services
  tags:
    - ipaserver
  firewalld: service={{ item }}
	     permanent=true
	     state=enabled
	     immediate=yes
  with_items:
    - http
    - https
    - ldap
    - ldaps
    - dns
    - kerberos
    - kpasswd
    - ntp

- name: Open Firewall for ports
  tags:
    - ipaserver
  firewalld: port={{ item }}
	     permanent=true
	     state=enabled
	     immediate=yes
  with_items:
    - 9180/tcp
    - 9443-9446/tcp
    - 9701/tcp
    - 7389/tcp
    - 8443/tcp

- name: Fetch krb5config
  fetch: src=/etc/krb5.conf  dest={{ inventory_dir }}/krb5.conf  flat=yes